services:
  - type: web
    name: grading-system
    env: node
    plan: free
    buildCommand: npm install && npm run init-db
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    healthCheckPath: /
